services:
  - type: web
    name: manifest-futures-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true